steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/app', '--build-arg', 'API_URL=https://backend-l7bccxltpa-lz.a.run.app', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/app']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'app', '--image', 'gcr.io/$PROJECT_ID/app', '--region', 'europe-north1', '--platform', 'managed']
images:
- gcr.io/$PROJECT_ID/app
